from .base import *


html_title = 'Recipes and Apps'
cards_label = 'Recipes and other useful resources'
card_height = 210
cards = (
    {'title': 'Happy Cow',
     'subtitle': 'Mobile app and website',
     'link': 'https://www.happycow.net',
     'preview': '../templates/assets/happycow.png',
     'description': "Find vegan restaurants nearby.",
    },
    {'title': 'We Cook Vegan',
     'subtitle': 'Recipes, Youtube',
     'link': 'https://www.youtube.com/@WeCookVegan',
     'preview': '../templates/assets/we_cook_vegan.jpg',
     'description': "Here you will find healthy, tasty, quick, step-by-step plant-based vegan recipes with easy-to follow video instructions which are fun to watch too.",
    },
    {'title': 'Rainbow Plant Life',
     'subtitle': 'Recipes, Youtube',
     'link': 'https://www.youtube.com/@RainbowPlantLife',
     'preview': '../templates/assets/rainbow_plant_life.jpg',
     'description': "Nisha shares everything from fancy date-night meals to Indian dishes from her childhood to meal prep guides that will help you eat well all week long. Her goal is for you to become the best plant-based home cook you can be.",
    },
    {'title': 'Andrew Bernard | The Nard Dog Cooks',
     'subtitle': 'Recipes, Youtube',
     'link': 'https://www.youtube.com/@thenarddogcooks',
     'preview': '../templates/assets/bernard.jpg',
     'description': "Vegan recipes from Andrew Bernard.",
    },
    {'title': 'Veganuary',
     'subtitle': 'Recipes',
     'link': 'https://veganuary.com/recipes/',
     'preview': 'https://veganuary.com/wp-content/uploads/2022/07/recipe-header-jpeg-800x533.jpeg',
     'description': "Veganuary is a non-profit organisation that encourages people worldwide to try vegan for January and beyond. Millions of people have signed up to our one-month vegan pledge since 2014, and in 2024 alone more than 2,100 new vegan products and menu options were launched for Veganuary globally.",
    },
    {'title': 'Nutrition Facts',
     'subtitle': 'Nutrition',
     'link': 'https://nutritionfacts.org/',
     'preview': '../templates/assets/nutritionfacts_dr-greger.jpg',
     'description': "Find out what the latest science is saying about your favorite foods to help you make the healthiest choices for you and your family.",
    },
    {'title': 'The Vegan Calculator',
     'subtitle': 'Website',
     'link': 'https://thevegancalculator.com/',
     'preview': '../templates/assets/calculator.png',
     'description': "A Vegan lifestyle saves animals, the environment & much more. Calculate how much you've saved.",
    },
    {'title': 'Vegan Bootcamp - Courses',
     'subtitle': 'Website',
     'link': 'https://veganbootcamp.org/courses',
     'preview': '../templates/assets/bootcamp.png',
     'description': "The courses from Vegan Bootcamp are going to give you the basic idea of where to start and what you should do.",
    },
    {'title': 'Wild Animal Suffering',
     'subtitle': 'Website',
     'link': 'https://wildanimalsuffering.org/',
     'preview': '../templates/assets/wildsuffer.png',
     'description': "An overview of wild animal suffering, why it matters, and what we can do to help.",
    },
    {'title': 'Vegan Cheat Sheet',
     'subtitle': 'Google Sheet',
     'link': 'https://vegancheatsheet.org/',
     'preview': '../templates/assets/cheatsheet.png',
     'description': "A HUGE collection of vegan resources: communities, studies, fashion, podcasts, celebrities and a lot lot more.",
    },
)
