html_title = 'Films'
cards_label = 'Selected Films'
cards = (
    {'title': 'Earthlings',
     'subtitle': '2005',
     'link': 'https://youtu.be/3XrY2TP0ZyU',
     'preview': '/_media/earthlings.jpg',
     'description': "Narrated by Joaquin Phoenix, writer/director Shaun Monson's 2005 documentary about humanity's economic dependence and treatment of animals is a sobering, hard-hitting reality check into the pet, food, clothing, entertainment, and scientific industries.",
    },
    {'title': 'What the Health',
     'subtitle': '2017, Netflix',
     'link': 'https://www.youtube.com/watch?v=SN9hIRM3R0A',
     'preview': '/_media/what_the_health.jpg',
     'description': "This documentary film critiques the health impact of meat, fish, eggs and dairy products consumption, and questions the practices of leading health and pharmaceutical organizations. Its primary purpose is to advocate for a plant-based diet.",
    },
    {'title': 'You Are What You Eat: A Twin Experiment',
     'subtitle': '2024, Netflix',
     'link': 'https://opsociety.org/ops-productions/films/you-are-what-you-eat-a-twin-experiment/',
     'preview': '/_media/twins.jpg',
     'description': 'Identical twins change their diets and lifestyles for eight weeks in a unique scientific experiment designed to explore how certain foods impact the body.',
    },
    {'title': 'Cowspiracy',
     'subtitle': '2014',
     'link': 'https://www.youtube.com/watch?v=UsigH2Skfdg',
     'preview': '/_media/cowspiracy.jpg',
     'description': 'Follow the shocking, yet humorous, journey of an aspiring environmentalist, as he daringly seeks to find the real solution to the most pressing environmental issues and true path to sustainability.',
    },
    {'title': 'Seaspiracy',
     'subtitle': '2021, Netflix',
     'link': 'https://www.netflix.com/nl-en/title/81014008',
     'preview': '/_media/seaspiracy.jpg',
     'description': 'Passionate about ocean life, a filmmaker sets out to document the harm that humans do to marine species — and uncovers alarming global corruption.',
    },
    {'title': 'Okja',
     'subtitle': '2017, Netflix',
     'link': 'https://www.netflix.com/nl-en/title/80091936',
     'preview': '/_media/okja.jpg',
     'description': 'A gentle giant and the girl who raised her are caught in the crossfire between animal activism, corporate greed and scientific ethics.',
    },
    {'title': 'The Game Changers',
     'subtitle': '2018',
     'link': 'https://www.youtube.com/watch?v=MIl6aRS452E',
     'preview': '/_media/gamechangers.jpg',
     'description': 'The Game Changers tells the story of James Wilks – elite Special Forces trainer and The Ultimate Fighter winner – as he travels the world on a quest to uncover the optimal diet for human performance. Showcasing elite athletes, special ops soldiers, visionary scientists, cultural icons, and everyday heroes, what James discovers permanently changes his understanding of food and his definition of true strength.',
    },
    {'title': 'Dominion',
     'subtitle': '2018',
     'link': 'https://www.youtube.com/watch?v=LQRAfJyEsko',
     'preview': '/_media/dominion.jpg',
     'description': "Dominion uses drones, hidden and handheld cameras to expose the dark underbelly of modern animal agriculture, questioning the morality and validity of humankind’s dominion over the animal kingdom. While mainly focusing on animals used for food, it also explores other ways animals are exploited and abused by humans, including clothing, entertainment and research.",
    },
    {'title': 'Norm',
     'subtitle': '2017',
     'link': 'https://www.youtube.com/watch?v=poxl0K9UrP0',
     'preview': '/_media/norm.jpg',
     'description': "A short film about two roommates debating over the morality of rape, in a society where raping women is legal and socially accepted.",
    },
    {'title': 'The Most Important Speech You Will Ever Hear',
     'subtitle': '2010',
     'link': 'https://www.youtube.com/watch?v=U5hGQDLprA8',
     'preview': '/_media/most_speech.jpg',
     'description': "An inspirational life-changing speech by Gary Yourofsky at Georgia Tech university, an animal liberation activist, national lecturer on animal rights and veganism, and founder of ADAPTT, a non-profit US organization.",
    },
    {'title': 'Milk: Make Your Own Mind Up',
     'subtitle': '2021',
     'link': 'https://www.youtube.com/watch?v=d5wabeFG9pM',
     'preview': '/_media/milkmind.jpg',
     'description': "In this documentary, Joey Carbstrong presents the horrifying reality of the dairy industry, of which ordinary consumers are mostly unaware. From forced artificial insemination to farming and ultimately to slaughter: Every bottle of milk contains this reality.",
    },
    {'title': 'Pignorant',
     'subtitle': '2024',
     'link': 'https://pignorantfilm.com/',
     'preview': '/_media/pignorant.jpg',
     'description': "An ex gang member’s love for pigs spurs him on a life-risking mission to uncover the truth behind ‘bacon’",
    },
    {'title': 'The Smell of Money',
     'subtitle': '2022',
     'link': 'https://www.smellofmoneydoc.com/',
     'preview': '/_media/monsmell.jpg',
     'description': "“The smell of money” — that’s what Big Pork calls the stench of pig waste in the air in eastern North Carolina, where much of the world’s bacon and barbecue is made. But to Elsie Herring and others who live near the state’s giant pig factories, the revolting odor is a call to battle against generations of injustice.",
    },
    {'title': 'Vegucated',
     'subtitle': '2011',
     'link': 'https://www.youtube.com/watch?v=CrWx_e1wuZQ',
     'preview': '/_media/vegucated.jpg',
     'description': "Vegucated is a feature-length documentary that follows three meat- and cheese-loving New Yorkers who agree to adopt a vegan diet for six weeks.",
    },
    {'title': 'The End Of Meat',
     'subtitle': '2017',
     'link': 'https://archive.org/details/2017-the-end-of-meat-1280x-544',
     'preview': '/_media/meatend.jpg',
     'description': "The End of Meat is a groundbreaking documentary film envisioning a future where meat consumption belongs to the past.",
    },
    {'title': 'Poisoned',
     'subtitle': '2023',
     'link': 'https://www.netflix.com/title/81460481',
     'preview': '/_media/poisoned.jpg',
     'description': "Through revealing interviews with experts and victims' families, this gripping documentary examines the problem of deadly foodborne illness in the US.",
    },
    {'title': 'The Cove',
     'subtitle': '2009',
     'link': 'https://ihavenotv.com/the-cove',
     'preview': '/_media/thecove.jpg',
     'description': "In Taiji, Japan, local fishermen hide a gruesome secret: the capture and slaughter of dolphins. Activist Ric O'Barry, who trained dolphins for the 'Flipper' TV series, joins forces with filmmaker Louis Psihoyos and the Ocean Preservation Society to expose the brutal practice, risking life and limb in the process.",
    },
    {'title': 'Blackfish',
     'subtitle': '2013',
     'link': 'https://archive.org/details/2013-blackfish',
     'preview': '/_media/blackfish.jpg',
     'description': "The documentary concerns the captivity of Tilikum, an orca involved in the deaths of three individuals, and the consequences of keeping orcas in captivity. The coverage of Tilikum includes his capture in 1983 off the coast of Iceland and his purported harassment by fellow captive orcas at Sealand of the Pacific.",
    },
    {'title': 'Forks Over Knives',
     'subtitle': '2011',
     'link': 'https://www.forksoverknives.com/the-film/',
     'preview': '/_media/forksoverknives.png',
     'description': "What if one simple change could save you from chronic diseases such as diabetes and heart disease? Take a deep dive into the plant-based diet documentary that has influenced millions around the world.",
    },
    {'title': 'Land of hope and glory',
     'subtitle': '2017',
     'link': 'https://www.landofhopeandglory.org/',
     'preview': '/_media/landofhope.jpg',
     'description': "Documentary about the hidden truth behind UK animal farming.",
    },
    {'title': 'Milked',
     'subtitle': '2021',
     'link': 'https://milked.film/',
     'preview': '/_media/milked.webp',
     'description': "A young activist goes deep into dairy land where he takes on the giants of New Zealand’s most powerful industry, and reveals how the sacred cash-cow industry has been milked dry.",
    },
    {'title': 'Slay',
     'subtitle': '2022',
     'link': 'https://www.slay.film/',
     'preview': '/_media/slay.webp',
     'description': "A documentary going behind the scenes of the fashion industry to investigate fur, leather and wool, greenwashing and the impact of brands using animal skins on people, planet and animals.",
    },
    {'title': 'Soul in the Sea',
     'subtitle': '2013',
     'link': 'https://www.imdb.com/title/tt2992204',
     'preview': '/_media/soulsea.webp',
     'description': "The true story of one woman's quest to befriend and protect and extroverted wild dolphin, Moko. Filmed in the 6 months leading up to Moko's death, Soul in the Sea follows a journey of discovery, devastating loss, and resolution. It's a love story with a difference.",
    },
)
