html_title = 'Global statistics'
cards_label = html_title
card_height = 210
cards = (
    {'title': 'Half of the world’s habitable land is used for agriculture',
     'subtitle': 'ourworldindata.org',
     'link': 'https://ourworldindata.org/global-land-for-agriculture',
     'preview': '/_media/landuse.png',
     'description': "More than three-quarters of global agricultural land is used for livestock, despite meat and dairy making up a much smaller share of the world's protein and calories.",
    },
    {'title': 'Food production is responsible for one-quarter of the world’s greenhouse gas emissions',
     'subtitle': 'ourworldindata.org',
     'link': 'https://ourworldindata.org/food-ghg-emissions',
     'preview': '/_media/emissions.png',
     'description': "One-quarter of the world's greenhouse gas emissions result from food and agriculture. What are the main contributors to food's emissions?",
    },
    {'title': 'Where does the plastic in our oceans come from?',
     'subtitle': 'ourworldindata.org',
     'link': 'https://ourworldindata.org/ocean-plastics',
     'preview': '/_media/mismanaged.png',
     'description': "Which countries and rivers emit the most plastic to the ocean? What does this mean for solutions to tackle plastic pollution?",
    },
    {'title': 'Cutting down forests: what are the drivers of deforestation?',
     'subtitle': 'ourworldindata.org',
     'link': 'https://ourworldindata.org/what-are-drivers-deforestation',
     'preview': '/_media/deforestation.png',
     'description': "Three-quarters of deforestation is driven by agriculture. Most comes from the production of beef, palm oil, soy and logging industries.",
    },
    {'title': 'We could reduce the amount of land used for grazing and croplands used to grow animal feed',
     'subtitle': 'ourworldindata.org',
     'link': 'https://ourworldindata.org/land-use-diets',
     'preview': '/_media/agriculture.png',
     'description': "If the world adopted a plant-based diet, we would reduce global agricultural land use from 4 to 1 billion hectares",
    },
    {'title': '‘The anti-livestock people are a pest’: how UN food body played down role of farming in climate change',
     'subtitle': 'The Guardian',
     'link': 'https://www.theguardian.com/environment/2023/oct/20/the-anti-livestock-people-are-a-pest-how-un-fao-played-down-role-of-farming-in-climate-change',
     'preview': '/_media/un_guardian.png',
     'description': "Ex-officials at the Food and Agriculture Organization say its leadership censored and undermined them when they highlighted how livestock methane is a major greenhouse gas.",
    },
)
